const cars = [
  {
    id: 1,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSSj_5K81Cynmj8vAu3zZwcTPG9yAcvBcSwLFhNT7rVaA&s=10",
    featured: true,
    price: "₹ 8,88,888",
    year: 2022,
    km: "21,000 km",
    name: "Mahindra Thar",
    location: "Monipnur",
    date: "Jul 12",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 2,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMd4aMRxEF1tX5VtLRSNkmV68dHBF4lXNk0WXgcES5nQ&s=10",
    featured: true,
    price: "₹ 12,50,000",
    year: 2021,
    km: "59,000 km",
    name: "Mahindra Thar",
    location: "Napler Town",
    date: "Jul 21",
    warranty: false,
    documentTransfer: true
  },
  {
    id: 3,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcReYdNz--S_cRynsGhSISHJf2F_yD9acAJdALvH_1X7DA&s=10",
    featured: true,
    olx: true,
    price: "₹ 7,25,000",
    year: 2019,
    km: "68,000 km",
    name: "Hyundai Venue",
    location: "Dr Mukherjee Nagar",
    date: "Jan 18",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 4,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRY0HwZPcAv12aXXG0PLKp-5lgOAmOms9PVjFJkrhaeTw&s=10",
    featured: false,
    price: "₹ 10,75,000",
    year: 2020,
    km: "45,000 km",
    name: "Hyundai Creta",
    location: "Rohini",
    date: "Feb 10",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 5,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcT3xEed7IxH5ZDZtzYjobcU8U0wUk71Q-Ds-zDr0JCbag&s=10",
    featured: true,
    price: "₹ 5,85,000",
    year: 2021,
    km: "32,000 km",
    name: "Maruti Swift",
    location: "Laxmi Nagar",
    date: "Mar 05",
    warranty: false,
    documentTransfer: true
  },
  {
    id: 6,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcXht04rbOUXnCmF8Tmr7jCZF2-pRJs4TMC96JGeLzbg&s",
    featured: false,
    price: "₹ 6,45,000",
    year: 2022,
    km: "25,000 km",
    name: "Maruti Baleno",
    location: "Dwarka",
    date: "Mar 18",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 7,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTsYKutYVOtoD0VgUvr2dNprcXflHRq_A_XWF-1ZcVFEg&s=10",
    featured: true,
    price: "₹ 28,50,000",
    year: 2020,
    km: "55,000 km",
    name: "Toyota Fortuner",
    location: "Saket",
    date: "Apr 02",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSTtELOU6O7b4W6KwHUiWWrdKZpjHv23D7irNAfwpvIIw&s=10",
    featured: false,
    price: "₹ 8,20,000",
    year: 2021,
    km: "38,000 km",
    name: "Tata Nexon",
    location: "Pitampura",
    date: "Apr 15",
    warranty: false,
    documentTransfer: true
  },
  {
    id: 9,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQuCBxUkSoUy8MOYfakSL_j8m0MLi7_-7qNvG8Uhrd4tg&s=10",
    featured: true,
    price: "₹ 6,90,000",
    year: 2022,
    km: "19,000 km",
    name: "Tata Punch",
    location: "Janakpuri",
    date: "May 01",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 10,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQpW0dacmheCmYXODad23-34JWmsiw5803Nza_WZQr2ng&s=10",
    featured: false,
    price: "₹ 9,75,000",
    year: 2020,
    km: "42,000 km",
    name: "Honda City",
    location: "Vasant Kunj",
    date: "May 12",
    warranty: true,
    documentTransfer: false
  },
  {
    id: 11,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSmRKcEIS4WkO8OQBuedjQXVs7b6sFkgQUjXfeMvGWO7g&s=10",
    featured: true,
    price: "₹ 8,95,000",
    year: 2021,
    km: "35,000 km",
    name: "Hyundai Verna",
    location: "Karol Bagh",
    date: "May 25",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 12,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSQNZwBE3g7PuvbYH0jJ9pa8Ibod9qNtj-UUPoG6_u4iA&s=10",
    featured: false,
    price: "₹ 11,80,000",
    year: 2020,
    km: "48,000 km",
    name: "Kia Seltos",
    location: "Noida",
    date: "Jun 03",
    warranty: false,
    documentTransfer: true
  },
  {
    id: 13,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSKiC68jpsG1dWzaxXNw0iT950JKy7PKBChnommhvzHsA&s=10",
    featured: true,
    price: "₹ 8,40,000",
    year: 2022,
    km: "22,000 km",
    name: "Kia Sonet",
    location: "Gurgaon",
    date: "Jun 10",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 14,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSuvt6z3R1i6q4PJ5Q7o1tlN8Sz8bgNo8l6FnTUbVzlaA&s=10",
    featured: false,
    price: "₹ 13,25,000",
    year: 2021,
    km: "41,000 km",
    name: "Tata Harrier",
    location: "Greater Noida",
    date: "Jun 18",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 15,
    image: "https://cdn-s3.autocarindia.com/legacy/cdni/mmv_images/colors/20250714125759_Mahindra_Scorpio_Classic_Stealth_Black[1].jpg?w=728&q=75&fm=auto",
    featured: true,
    price: "₹ 14,50,000",
    year: 2020,
    km: "52,000 km",
    name: "Mahindra Scorpio",
    location: "Najafgarh",
    date: "Jun 25",
    warranty: false,
    documentTransfer: true
  },
  {
    id: 16,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSqpGbRxKJYdQePoKXy2n_iIq64V64jvGd7XlPZatIpSA&s=10",
    featured: false,
    price: "₹ 15,75,000",
    year: 2022,
    km: "28,000 km",
    name: "Mahindra XUV700",
    location: "Model Town",
    date: "Jul 02",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 17,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi773O34dcTw65OS4_0oSkee-hR90-3tZD2ot217DuHw&s=10",
    featured: true,
    price: "₹ 14,20,000",
    year: 2021,
    km: "31,000 km",
    name: "Hyundai Alcazar",
    location: "Vikaspuri",
    date: "Jul 08",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 18,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSOsf7H9U3rLHOQ8Tutscy9izFUEtLhBfmuNaFlaGLkAA&s=10",
    featured: false,
    price: "₹ 6,75,000",
    year: 2020,
    km: "44,000 km",
    name: "Hyundai i20",
    location: "Shalimar Bagh",
    date: "Jul 15",
    warranty: false,
    documentTransfer: true
  },
  {
    id: 19,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSNn6hNgFOZmMeZKjlFm2sO18ajkW6ykDcasq1ilZIbYQ&s=10",
    featured: true,
    price: "₹ 7,80,000",
    year: 2019,
    km: "58,000 km",
    name: "Maruti Ciaz",
    location: "Preet Vihar",
    date: "Jul 20",
    warranty: true,
    documentTransfer: true
  },
  {
    id: 20,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTQPBry_ouBMiILuMrY0Fl_ZX9--mqepcjLEuXz3CjJgA&s=10",
    featured: false,
    price: "₹ 5,95,000",
    year: 2018,
    km: "72,000 km",
    name: "Renault Duster",
    location: "Uttam Nagar",
    date: "Jul 25",
    warranty: false,
    documentTransfer: false
  }
];

export default cars;